### ISSUE TITLE
Way to avoid hard coding events

### ISSUE THREAD

**Issue by muhakh** [joomla-projects/gsoc16_recording-action-logs#10]
I have a question
I think that these events are the events that should be logged:
- onContentAfterSave
- onContentAfterDelete
- onContentChangeState
- onExtensionAfterInstall
- onExtensionAfterUninstall
- onExtensionAfterUpdate
- onUserAfterSave
- onUserAfterDelete
- onUserAfterSaveGroup
- onUserAfterDeleteGroup

Are there any other events that needs to be logged?

**Comment by Llewellynvdm** [comment]
Could you make it that the events are stored in the db or in an XML and that more events can be added or some removed? so that it is not hard coded?

That way the component will be extendable to third party components, that is a good list as a starting point.

Something like this:

```
class PlgSystemUserLogs extends JPlugin
{

    private $events = array();

    function __construct(&$subject, $config = array())
    {
        // load the events
        $this->events = $this->getEventsToLog(); // <-- from DB or XML
        foreach ($this->events as $event => $configEvent)
        {
            $this->$event = function() use($configEvent) {
                // build a switch for all joomla default events
                // and a default (basic) behavior for custom, thridparty events
                $this->addLogsToDB($message, $strContext);
            };
        }
        parent::__construct($subject, $config);
    }
}
```

Not sure if it will work, just an idea. Wonder if you could test  and try it?

**Comment by muhakh** [comment]
I think that's a great idea. I'll give it a try

**Comment by muhakh** [comment]
I'm sorry Llewellyn, I tried hard but I can't understand the solution and it didn't work with me.
For example:How can I pass the parameter (like:$article or $context) of events?

**Comment by Llewellynvdm** [comment]
I have not had the time yet to go deep into the JPlugin & JEvent classes to see why those events as methods fire.

That could be a good thing to do... /libraries/cms/plugin/plugin.php && /libraries/joomla/event/event.php

It can very well be that my idea can't work. But that there is some other way. I will take a closer look this evening if some of the other mentors have not since then come up with a better idea.

**Comment by muhakh** [comment]
I think it can't be implemented as the `trigger` method in the `JEventDispatcher` class uses `call_user_func_array` which means the event functions needs to be defined as a part of the plugin class.
Waiting for other opinions.

**Comment by Llewellynvdm** [comment]
Okay I see there is a method in /libraries/joomla/event/event.php that could be over written called the update method.

```
    /**
     * Method to trigger events.
     * The method first generates the even from the argument array. Then it unsets the argument
     * since the argument has no bearing on the event handler.
     * If the method exists it is called and returns its return value. If it does not exist it
     * returns null.
     *
     * @param   array  &$args  Arguments
     *
     * @return  mixed  Routine return value
     *
     * @since   11.1
     */
    public function update(&$args)
    {
        // First let's get the event from the argument array.  Next we will unset the
        // event argument as it has no bearing on the method to handle the event.
        $event = $args['event'];
        unset($args['event']);

        /*
         * If the method to handle an event exists, call it and return its return
         * value.  If it does not exist, return null.
         */
        if (method_exists($this, $event))
        {
            return call_user_func_array(array($this, $event), $args);
        }
        else
        {
            return null;
        }
    }
```

Have you given it a look? I wonder if updating this methods way of calling the events would help making it dynamic.

I could write something up, but why don't you give it a try. If you feel it is not worth the effort then dump this idea and go with what works for you.

**Comment by Llewellynvdm** [comment]
It seems like the _JEventDispatcher_ in its trigger method on line 160 calls the update method of the plugin that it inherited from JEvent. 

I have asked other Developers to give their input on the subject, since I am not sure if there is possible a convention that I have missed.

Reality is we should not let this keep you back.

You can always latter with further iteration improve the implementation from hard code to something more dynamic.

**So if you would like to start with only those events mentioned, that is also great!**

You do know of this [list of events](https://docs.joomla.org/Plugin/Events) right? So if those you have selected are all you feel should be targeted, then do it in a way that will make it easy to add more if needed.

**Comment by chrisdavenport** [comment]
Each of the events has a different method signature, so you're not going to be able to reliably create a single method to handle them all.  But what you can do is create an addLogEntry method which will become the standard API for saving event data in the log database.  Each event handler method can then be seen as merely mapping data from the event to the event store (database).

If I understand correctly, the problem you're trying to solve is to be able to handle (log) new event types that might be created by third-party developers.  I would just support the core events in the core plugin.  If third-parties want to add logging support for their own events, then they have only to create their own plugin to handle the event and use the same addLogEntry method.  There is no need for the core plugin to handle third-party events as the plugin system itself provides the mechanism for extending support to new event types.

Of course, this means that rendering of log entries in the Administrator UI will need to be generic so that third-party (or even future core) events make sense to users.

**Comment by shamsbd71** [comment]
agree with @chrisdavenport, Core plugin should handle or trigger core events and core events can be called from any other third party extensions.

a good example can be this file:
https://github.com/joomla-projects/joomla-cms/blob/master/plugins/content/joomla/joomla.php

just make sure that any third party plugin can hook the event and pass necessary info and this plugin will store the logs. 
content plugin joomla has a filter like this:

```
// Check we are handling the frontend edit form.
if ($context != 'com_content.form')
{
    return true;
}
```

i suggest not to add anything like that as its not gonna call so random

**Comment by Llewellynvdm** [comment]
Thanks @chrisdavenport for looking at this issue, I fully agree with your way of implementation. This certainly seems like a more reasonable solution.

**Comment by coolbung** [comment]
Agree that the implementation needs to be like the way @chrisdavenport suggested. Further, I would also propose that you look at the existing implementation in `libraries/joomla/log` This is the core logger. It would be great if you could extend the core logger to add the event logging feature. (This would mean a database change, so will need to be carefully discussed)

If we decide to do this separately, then here's my recommendation on go to go about it
- Start by proposing a database structure (couldn't find it in the Wiki)
- Suggest a new library that would be created (say libraries/joomla/audittral), however you should ideally be able to use the various adapters from `libraries/joomla/log/logger`
- Write a Plugin that will catch and log the core extension events
